  // Dummy Product List
  import 'package:kkn_store/utils/constants/image_strings.dart';

const List<Map<String, dynamic>> products = [
    {
      "title": "Nike Go FlyEase Women's Easy On/Off Shoes Size 7 (Black)",
      "brand": "Levi's",
      "image": TImages.product2,
      "price": "128.95",
      "discount": "40%",
    },
    {
      "title": "Red Tap Men's Casual Sneaker Shoes",
      "brand": "Red Tape",
      "image": TImages.product1,
      "price": "35.51",
      "discount": "7%",
    },
    {
      "title": "Prada Leather Saffiano Handbag",
      "brand": "Prada",
      "image": TImages.product3,
      "price": "3501.27",
      "discount": "6%",
    },
    {
      "title": "Prada Sunglasses PR17WS 16K40J",
      "brand": "Prada",
      "image": TImages.product4,
      "price": "298.70",
      "discount": "34%",
    },
    // {
    //   "title": "Nike Smartwatch",
    //   "brand": "Nike",
    //   "image": TImages.product4,
    //   "price": "322.45",
    //   "discount": "43%",
    // },
    // {"title": "Fossil Smartwatch", "brand": "Fossil", "image": TImages.product9, "price": "671.39", "discount": "28%"},
    // {"title": "Red Tape Keyboard", "brand": "Red Tape", "image": TImages.product1, "price": "847.06", "discount": "48%"},
    // {"title": "Puma Pocket", "brand": "Puma", "image": TImages.product3, "price": "567.24", "discount": "30%"},
    // {"title": "Zara Monitor", "brand": "Zara", "image": TImages.product6, "price": "555.12", "discount": "43%"},
    // {"title": "HP Keyboard", "brand": "HP", "image": TImages.product3, "price": "527.01", "discount": "30%"},
    // {"title": "Apple iPhone", "brand": "Apple", "image": TImages.product2, "price": "999.99", "discount": "10%"},
    // {"title": "Samsung Galaxy Watch", "brand": "Samsung", "image": TImages.product3, "price": "249.99", "discount": "15%"},
    // {"title": "Sony Headphones", "brand": "Sony", "image": TImages.product4, "price": "199.99", "discount": "20%"},
    // {"title": "Adidas Running Shoes", "brand": "Adidas", "image": TImages.product5, "price": "129.99", "discount": "25%"},
    // {"title": "Zara Tote Bag", "brand": "Zara", "image": TImages.product6, "price": "89.99", "discount": "30%"},
    // {"title": "Levi's Jeans", "brand": "Levi's", "image": TImages.product7, "price": "59.99", "discount": "35%"},
    // {"title": "Apple MacBook", "brand": "Apple", "image": TImages.product8, "price": "1299.99", "discount": "5%"},
    // {"title": "HP Pavilion Laptop", "brand": "HP", "image": TImages.product9, "price": "849.99", "discount": "10%"},
    // {"title": "Nike Gym Bag", "brand": "Nike", "image": TImages.product10, "price": "49.99", "discount": "20%"},
    // {"title": "Fossil Wallet", "brand": "Fossil", "image": TImages.product1, "price": "39.99", "discount": "25%"},
    // {"title": "Dell Monitor", "brand": "Dell", "image": TImages.product2, "price": "299.99", "discount": "15%"},
    // {"title": "Apple AirPods", "brand": "Apple", "image": TImages.product3, "price": "159.99", "discount": "10%"},
    // {"title": "Samsung Tablet", "brand": "Samsung", "image": TImages.product4, "price": "329.99", "discount": "12%"},
    // {"title": "Sony Bluetooth Speaker", "brand": "Sony", "image": TImages.product5, "price": "89.99", "discount": "18%"},
    // {"title": "Adidas Sweatshirt", "brand": "Adidas", "image": TImages.product6, "price": "69.99", "discount": "30%"},
    // {"title": "Zara Sunglasses", "brand": "Zara", "image": TImages.product7, "price": "39.99", "discount": "22%"},
    // {"title": "Levi's Shirt", "brand": "Levi's", "image": TImages.product8, "price": "49.99", "discount": "35%"},
    // {"title": "Puma Cap", "brand": "Puma", "image": TImages.product9, "price": "19.99", "discount": "40%"},
    // {"title": "Fossil Belt", "brand": "Fossil", "image": TImages.product10, "price": "29.99", "discount": "25%"},
    // {"title": "Nike Socks", "brand": "Nike", "image": TImages.product1, "price": "14.99", "discount": "15%"},
    // {"title": "Zara Backpack", "brand": "Zara", "image": TImages.product2, "price": "79.99", "discount": "30%"},
    // {"title": "HP Wireless Mouse", "brand": "HP", "image": TImages.product3, "price": "24.99", "discount": "20%"},
    // {"title": "Apple Watch", "brand": "Apple", "image": TImages.product4, "price": "399.99", "discount": "5%"},
    // {"title": "Sony Camera", "brand": "Sony", "image": TImages.product5, "price": "649.99", "discount": "12%"},
    // {"title": "Samsung TV", "brand": "Samsung", "image": TImages.product6, "price": "899.99", "discount": "18%"},
    // {"title": "Dell Desktop", "brand": "Dell", "image": TImages.product7, "price": "1099.99", "discount": "8%"},
    // {"title": "Levi's Jacket", "brand": "Levi's", "image": TImages.product8, "price": "99.99", "discount": "30%"},
    // {"title": "Nike Track Pants", "brand": "Nike", "image": TImages.product9, "price": "59.99", "discount": "20%"},
    // {"title": "Puma Sports T-Shirt", "brand": "Puma", "image": TImages.product10, "price": "39.99", "discount": "35%"},
    // {"title": "Tommy Hilfiger Leather Wallet", "brand": "Tommy Hilfiger", "image": TImages.product1, "price": "49.99", "discount": "20%"},
    // {"title": "Calvin Klein Running Shoes", "brand": "Calvin Klein", "image": TImages.product2, "price": "89.99", "discount": "30%"},
    // {"title": "Gucci Tote Bag", "brand": "Gucci", "image": TImages.product3, "price": "799.99", "discount": "10%"},
    // {"title": "Michael Kors Watch", "brand": "Michael Kors", "image": TImages.product4, "price": "299.99", "discount": "15%"},
    // {"title": "Ray-Ban Sunglasses", "brand": "Ray-Ban", "image": TImages.product5, "price": "149.99", "discount": "18%"},
    // {"title": "North Face Jacket", "brand": "North Face", "image": TImages.product6, "price": "129.99", "discount": "25%"},
    // {"title": "Apple iPad", "brand": "Apple", "image": TImages.product7, "price": "599.99", "discount": "8%"},
    // {"title": "Sony PlayStation Controller", "brand": "Sony", "image": TImages.product8, "price": "69.99", "discount": "12%"},
    // {"title": "Bose Noise Cancelling Headphones", "brand": "Bose", "image": TImages.product9, "price": "349.99", "discount": "20%"},
    // {"title": "Adidas Soccer Ball", "brand": "Adidas", "image": TImages.product10, "price": "29.99", "discount": "22%"},
    // {"title": "Nike Basketball Shoes", "brand": "Nike", "image": TImages.product1, "price": "119.99", "discount": "15%"},
    // {"title": "Under Armour Sports T-Shirt", "brand": "Under Armour", "image": TImages.product2, "price": "34.99", "discount": "28%"},
    // {"title": "Patagonia Hiking Backpack", "brand": "Patagonia", "image": TImages.product3, "price": "199.99", "discount": "18%"},
    // {"title": "Dell XPS Laptop", "brand": "Dell", "image": TImages.product4, "price": "1299.99", "discount": "7%"},
    // {"title": "Samsung Soundbar", "brand": "Samsung", "image": TImages.product5, "price": "249.99", "discount": "14%"},
    // {"title": "HP Office Printer", "brand": "HP", "image": TImages.product6, "price": "149.99", "discount": "12%"},
    // {"title": "Apple Magic Keyboard", "brand": "Apple", "image": TImages.product7, "price": "99.99", "discount": "5%"},
    // {"title": "Lenovo Gaming Laptop", "brand": "Lenovo", "image": TImages.product8, "price": "1099.99", "discount": "10%"},
    // {"title": "Amazon Echo Dot", "brand": "Amazon", "image": TImages.product9, "price": "49.99", "discount": "20%"},
    // {"title": "Fitbit Charge 5", "brand": "Fitbit", "image": TImages.product10, "price": "129.99", "discount": "15%"},
    // {"title": "Canon DSLR Camera", "brand": "Canon", "image": TImages.product1, "price": "899.99", "discount": "10%"},
    // {"title": "Nikon Zoom Lens", "brand": "Nikon", "image": TImages.product2, "price": "349.99", "discount": "12%"},
    // {"title": "Sony Action Camera", "brand": "Sony", "image": TImages.product3, "price": "199.99", "discount": "15%"},
    // {"title": "Garmin GPS Watch", "brand": "Garmin", "image": TImages.product4, "price": "249.99", "discount": "18%"},
    // {"title": "Levi's Denim Jacket", "brand": "Levi's", "image": TImages.product5, "price": "79.99", "discount": "25%"},
    // {"title": "Converse Chuck Taylor Shoes", "brand": "Converse", "image": TImages.product6, "price": "59.99", "discount": "20%"},
    // {"title": "Columbia Winter Gloves", "brand": "Columbia", "image": TImages.product7, "price": "29.99", "discount": "30%"},
    // {"title": "North Face Beanie", "brand": "North Face", "image": TImages.product8, "price": "24.99", "discount": "22%"},
    // {"title": "Apple iMac", "brand": "Apple", "image": TImages.product9, "price": "1799.99", "discount": "5%"},
    // {"title": "Samsung Galaxy Buds", "brand": "Samsung", "image": TImages.product10, "price": "99.99", "discount": "15%"},
    // {"title": "Microsoft Surface Pro", "brand": "Microsoft", "image": TImages.product1, "price": "999.99", "discount": "10%"},
    // {"title": "Google Pixel Phone", "brand": "Google", "image": TImages.product2, "price": "799.99", "discount": "8%"},
    // {"title": "Bose Portable Speaker", "brand": "Bose", "image": TImages.product3, "price": "199.99", "discount": "15%"},
    // {"title": "JBL Bluetooth Speaker", "brand": "JBL", "image": TImages.product4, "price": "89.99", "discount": "20%"},
    // {"title": "Nike Hoodie", "brand": "Nike", "image": TImages.product5, "price": "59.99", "discount": "25%"},
    // {"title": "Adidas Track Jacket", "brand": "Adidas", "image": TImages.product6, "price": "69.99", "discount": "20%"},
    // {"title": "Puma Running Shorts", "brand": "Puma", "image": TImages.product7, "price": "39.99", "discount": "30%"},
    // {"title": "Timberland Boots", "brand": "Timberland", "image": TImages.product8, "price": "129.99", "discount": "15%"},
    // {"title": "Ray-Ban Aviator Sunglasses", "brand": "Ray-Ban", "image": TImages.product9, "price": "159.99", "discount": "18%"},
    // {"title": "Michael Kors Purse", "brand": "Michael Kors", "image": TImages.product10, "price": "249.99", "discount": "10%"},
    // {"title": "Fossil Leather Belt", "brand": "Fossil", "image": TImages.product1, "price": "49.99", "discount": "25%"},
    // {"title": "Apple iPhone Charger", "brand": "Apple", "image": TImages.product2, "price": "29.99", "discount": "5%"},
    // {"title": "Samsung Wireless Charger", "brand": "Samsung", "image": TImages.product3, "price": "34.99", "discount": "8%"},
    // {"title": "Dell USB Hub", "brand": "Dell", "image": TImages.product4, "price": "24.99", "discount": "12%"},
    // {"title": "HP Gaming Mouse", "brand": "HP", "image": TImages.product5, "price": "39.99", "discount": "10%"},
    // {"title": "Canon Printer Ink", "brand": "Canon", "image": TImages.product6, "price": "49.99", "discount": "15%"},
    // {"title": "Lenovo External Hard Drive", "brand": "Lenovo", "image": TImages.product7, "price": "89.99", "discount": "20%"},
    // {"title": "Amazon Kindle", "brand": "Amazon", "image": TImages.product8, "price": "129.99", "discount": "18%"},
    // {"title": "Fitbit Versa 3", "brand": "Fitbit", "image": TImages.product9, "price": "179.99", "discount": "12%"},
    // {"title": "Garmin Fitness Tracker", "brand": "Garmin", "image": TImages.product10, "price": "149.99", "discount": "15%"},
    // {"title": "Sony PlayStation 5", "brand": "Sony", "image": TImages.product1, "price": "499.99", "discount": "5%"},
    // {"title": "Xbox Series X", "brand": "Microsoft", "image": TImages.product2, "price": "499.99", "discount": "5%"},
  ];