import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:kkn_store/common/widgets/success_scren/success_screen.dart';
import 'package:kkn_store/data/repositories/orders/order_repository.dart';
import 'package:kkn_store/features/personalization/controllers/address_controller.dart';
import 'package:kkn_store/features/shop/controllers/cart_controller.dart';
import 'package:kkn_store/features/shop/models/order_model.dart';
import 'package:kkn_store/navigation_menu.dart';
import 'package:kkn_store/utils/constants/image_strings.dart';
import 'package:kkn_store/utils/popups/loaders.dart';

class OrderController extends GetxController {
  static OrderController get instance => Get.find();

  final cartController = CartController.instance;
  final orderRepository = Get.put(OrderRepository());

  final RxBool isLoading = false.obs;

  Future<void> processOrder(double totalAmount) async {
    try {
      isLoading.value = true;
      TLoaders.customToast(message: 'Processing your order...');

      // 1. Create Order Model
      final order = OrderModel(
        id: '', // Generated by DB
        status: 'Pending',
        items: cartController.cartItems.toList(),
        totalAmount: totalAmount,
        orderDate: DateTime.now(),
        paymentMethod: 'QR Code',
        paymentStatus: 'Paid',
        shippingAddress: Get.find<AddressController>().selectedAddress.value.toJson(), // Save Address
      );

      // 2. Save Order
      await orderRepository.createOrder(order, cartController.cartItems);

      // 3. Clear Cart
      cartController.clearCart();

      // 4. Navigate to Success
      Get.offAll(() => SuccessScreen(
            image: TImages.successfulPaymentIcon,
            title: 'Payment Success!',
            subTitle: 'Your item will be shipped soon!',
            onPressed: () => Get.offAll(() => const NavigationMenu()),
          ));
    } catch (e) {
      String errorMessage = e.toString();
      
      // Handle "Insufficient stock" error from DB Trigger/RPC
      if (errorMessage.contains('Insufficient stock')) {
         errorMessage = 'One or more items are out of stock. Please adjust your cart.';
         // Optional: Regex to extract product ID and show name if possible
      }
      
      TLoaders.errorSnackBar(title: 'Order Failed', message: errorMessage);
    } finally {
      isLoading.value = false;
    }
  }
}
