// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0P9FC6f0lYQ9kuL7GH8nMSUF4HXr3zfY',
    appId: '1:273633259586:web:ef77a8d61d5c85e44b7ddb',
    messagingSenderId: '273633259586',
    projectId: 'kknstore-434e8',
    authDomain: 'kknstore-434e8.firebaseapp.com',
    storageBucket: 'kknstore-434e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjW1omKZ4LLkWKEfhp6LXJOWKsqiTnn54',
    appId: '1:273633259586:android:66a2a1e9de6b9aef4b7ddb',
    messagingSenderId: '273633259586',
    projectId: 'kknstore-434e8',
    storageBucket: 'kknstore-434e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Z1V6e5VAKjHvR31Q7Aq-iFtVajzhAGo',
    appId: '1:273633259586:ios:a4a5fca16a0c03f34b7ddb',
    messagingSenderId: '273633259586',
    projectId: 'kknstore-434e8',
    storageBucket: 'kknstore-434e8.firebasestorage.app',
    iosClientId: '273633259586-1hbe3ttu8dk5bbvb9jpl4daar7i2n2o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.kknStore',
  );

}